# 行列演算の基礎

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [2]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [4]:
# 行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [6]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [8]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# 行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よくある間違い

In [11]:
x = np.array([1,2,3])
x

array([1, 2, 3])

x.T #=> 二重かっこが安定

In [13]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [14]:
x.T

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理

In [23]:
X = np.array([
    [2,3,4],
    [1,2,3]
])
X

array([[2, 3, 4],
       [1, 2, 3]])

In [24]:
# 行と列の番号を取得
X.shape

(2, 3)

In [25]:
row, col = X.shape

In [26]:
row #=> 行

2

In [28]:
col #=> 列

3

In [29]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


# 練習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
,\ \boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$ のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

※　サンプル４個、入力変数２個（左の1はダミーデータ）

- Step1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- Step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- Step4: $\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [64]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])

print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [65]:
# yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])

print(y)

[[1]
 [5]
 [6]
 [8]]


In [37]:
#Step1
XtX = np.dot(X.T,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [40]:
#Step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [43]:
# Step3
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [48]:
# Step4
# w = XtX_inv * Xty 
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装

In [60]:
import sklearn

In [61]:
# 重回帰分析のみ読み込み(メモリの負担考慮)
from sklearn.linear_model import LinearRegression

In [62]:
# モデルの宣言
model = LinearRegression()

In [66]:
# モデルの学習　←　パラメータの調整
model.fit(X, y)

LinearRegression()

In [67]:
# 調整後のパラメータ （coefficient：係数）
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [68]:
model.intercept_ # intercept：切片

array([-0.14285714])

In [69]:
# 予測制度 ←　決定係数
model.score(X, y)

0.6923076923076923

In [70]:
# 予測値の計算
x = np.array([[1,2,3]])

In [72]:
y_pred = model.predict(x)
y_pred

array([[3.]])